name: Selenium headless crawl

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Google Chrome
      - uses: browser-actions/setup-chrome@v1

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          # or: pip install selenium

      - name: Run crawler
        # env:
        #   CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          python crawl.py

      - name: Commit artifacts to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add artifacts/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update crawl artifacts [skip ci]"
            git push origin HEAD:main
          fi
